# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Telegram Talk - Stickers"
tagline:             "A curated list of stickers for Telegram Talk."
description:         "Telegram Stickers Directory is a website dedicated to curating and promoting beautiful, cute, and fun stickers for Telegram Messenger. It’s run by two individuals who love using stickers just as much as you do, and we’ll do our best to keep this directory updated daily for your enjoyment."
url:                 "http://sticker.ttalk.me"
paginate:            15
paginate_path:       "/page/:num/"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              DevConcert
  url:               https://sticker.ttalk.me/
  email:             devconcert@devconcert.net

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/telegramtalk/telegramlk.github.io

# Collections
collections:
  stickers:
    output:       true
    permalink:    /:collection/:title/
